-- Pour Decisions — seed data
-- Run AFTER schema.sql. Safe to re-run (ON CONFLICT DO NOTHING).

INSERT INTO recipes (id, name, description, difficulty, serving_size, base_spirit, flavor_tags, ingredients, steps)
VALUES
  ('margarita-classic', 'Classic Margarita', 'A tart tequila sour with orange liqueur and a salted rim.', 'easy', 1, 'tequila', '["citrus", "tart", "refreshing"]'::jsonb, '[{"name": "tequila", "amount": 2, "unit": "oz"}, {"name": "lime juice", "amount": 1, "unit": "oz"}, {"name": "triple sec", "amount": 0.75, "unit": "oz"}, {"name": "salt", "amount": null, "unit": "rim"}]'::jsonb, '[{"order": 1, "action": "Rim a rocks glass with salt.", "tip": "Use a lime wedge to moisten the rim first."}, {"order": 2, "action": "Add tequila, lime juice, and triple sec to a shaker with ice."}, {"order": 3, "action": "Shake hard for 15 seconds until chilled."}, {"order": 4, "action": "Strain into the prepared glass over fresh ice."}]'::jsonb),
  ('paloma', 'Paloma', 'A bright tequila highball with grapefruit and lime.', 'easy', 1, 'tequila', '["citrus", "bubbly", "refreshing"]'::jsonb, '[{"name": "tequila", "amount": 2, "unit": "oz"}, {"name": "grapefruit soda", "amount": 4, "unit": "oz"}, {"name": "lime juice", "amount": 0.5, "unit": "oz"}, {"name": "salt", "amount": null, "unit": "pinch"}]'::jsonb, '[{"order": 1, "action": "Fill a tall glass with ice."}, {"order": 2, "action": "Pour in tequila and lime juice."}, {"order": 3, "action": "Top with grapefruit soda and a pinch of salt."}, {"order": 4, "action": "Stir gently and garnish with a grapefruit wedge."}]'::jsonb),
  ('moscow-mule', 'Moscow Mule', 'A crisp vodka cocktail with ginger beer and lime.', 'easy', 1, 'vodka', '["spicy", "citrus", "refreshing"]'::jsonb, '[{"name": "vodka", "amount": 2, "unit": "oz"}, {"name": "ginger beer", "amount": 4, "unit": "oz"}, {"name": "lime juice", "amount": 0.5, "unit": "oz"}, {"name": "mint", "amount": null, "unit": "sprig"}]'::jsonb, '[{"order": 1, "action": "Fill a mule mug with ice."}, {"order": 2, "action": "Add vodka and lime juice."}, {"order": 3, "action": "Top with ginger beer and stir gently."}, {"order": 4, "action": "Garnish with mint and a lime wedge."}]'::jsonb),
  ('cosmopolitan', 'Cosmopolitan', 'A pink vodka cocktail with cranberry and orange notes.', 'medium', 1, 'vodka', '["citrus", "fruity", "tart"]'::jsonb, '[{"name": "vodka", "amount": 1.5, "unit": "oz"}, {"name": "triple sec", "amount": 1, "unit": "oz"}, {"name": "cranberry juice", "amount": 0.5, "unit": "oz"}, {"name": "lime juice", "amount": 0.5, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Chill a coupe glass."}, {"order": 2, "action": "Add all ingredients to a shaker with ice."}, {"order": 3, "action": "Shake until very cold."}, {"order": 4, "action": "Double strain into the chilled glass.", "tip": "Express an orange peel over the surface if available."}]'::jsonb),
  ('espresso-martini', 'Espresso Martini', 'A rich vodka cocktail with espresso and coffee liqueur.', 'medium', 1, 'vodka', '["coffee", "rich", "smooth"]'::jsonb, '[{"name": "vodka", "amount": 1.5, "unit": "oz"}, {"name": "coffee liqueur", "amount": 1, "unit": "oz"}, {"name": "espresso", "amount": 1, "unit": "oz"}, {"name": "simple syrup", "amount": 0.25, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Chill a martini or coupe glass."}, {"order": 2, "action": "Add all ingredients to a shaker with plenty of ice."}, {"order": 3, "action": "Shake hard until the tin is frosty and the foam builds."}, {"order": 4, "action": "Double strain into the chilled glass.", "tip": "Three coffee beans make a classic garnish."}]'::jsonb),
  ('gin-and-tonic', 'Gin and Tonic', 'A clean, bitter highball with botanical gin and tonic water.', 'easy', 1, 'gin', '["bitter", "bubbly", "crisp"]'::jsonb, '[{"name": "gin", "amount": 2, "unit": "oz"}, {"name": "tonic water", "amount": 4, "unit": "oz"}, {"name": "lime wedge", "amount": 1, "unit": "piece"}]'::jsonb, '[{"order": 1, "action": "Fill a highball glass with fresh ice."}, {"order": 2, "action": "Pour in the gin."}, {"order": 3, "action": "Top with tonic water and give one gentle stir."}, {"order": 4, "action": "Squeeze in a lime wedge and drop it in."}]'::jsonb),
  ('tom-collins', 'Tom Collins', 'A sparkling gin sour with lemon and soda.', 'easy', 1, 'gin', '["citrus", "bubbly", "light"]'::jsonb, '[{"name": "gin", "amount": 2, "unit": "oz"}, {"name": "lemon juice", "amount": 1, "unit": "oz"}, {"name": "simple syrup", "amount": 0.5, "unit": "oz"}, {"name": "club soda", "amount": 2, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Add gin, lemon juice, and simple syrup to a shaker with ice."}, {"order": 2, "action": "Shake briefly until chilled."}, {"order": 3, "action": "Strain into a tall glass over fresh ice."}, {"order": 4, "action": "Top with club soda and garnish with a lemon wheel."}]'::jsonb),
  ('negroni', 'Negroni', 'A bittersweet stirred cocktail with gin, Campari, and vermouth.', 'medium', 1, 'gin', '["bitter", "herbal", "spirit-forward"]'::jsonb, '[{"name": "gin", "amount": 1, "unit": "oz"}, {"name": "campari", "amount": 1, "unit": "oz"}, {"name": "sweet vermouth", "amount": 1, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Add all ingredients to a mixing glass with ice."}, {"order": 2, "action": "Stir for 20 to 25 seconds until chilled and diluted."}, {"order": 3, "action": "Strain over a large cube in a rocks glass."}, {"order": 4, "action": "Express an orange peel over the drink and garnish."}]'::jsonb),
  ('daiquiri', 'Daiquiri', 'A classic rum sour that is crisp, bright, and balanced.', 'easy', 1, 'rum', '["citrus", "dry", "refreshing"]'::jsonb, '[{"name": "white rum", "amount": 2, "unit": "oz"}, {"name": "lime juice", "amount": 1, "unit": "oz"}, {"name": "simple syrup", "amount": 0.75, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Add all ingredients to a shaker with ice."}, {"order": 2, "action": "Shake hard until thoroughly chilled."}, {"order": 3, "action": "Double strain into a chilled coupe."}]'::jsonb),
  ('mojito', 'Mojito', 'A minty rum highball with lime and soda.', 'medium', 1, 'rum', '["minty", "citrus", "refreshing"]'::jsonb, '[{"name": "white rum", "amount": 2, "unit": "oz"}, {"name": "lime juice", "amount": 0.75, "unit": "oz"}, {"name": "simple syrup", "amount": 0.5, "unit": "oz"}, {"name": "mint leaves", "amount": 8, "unit": "leaf"}, {"name": "club soda", "amount": 2, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Gently muddle mint leaves with lime juice and simple syrup in a tall glass.", "tip": "Press lightly so the mint stays bright, not bitter."}, {"order": 2, "action": "Add rum and fill the glass with crushed ice."}, {"order": 3, "action": "Top with club soda and stir from the bottom up."}, {"order": 4, "action": "Crown with more crushed ice and a mint bouquet."}]'::jsonb),
  ('mai-tai', 'Mai Tai', 'A layered tiki rum drink with citrus and almond richness.', 'hard', 1, 'rum', '["tropical", "nutty", "citrus"]'::jsonb, '[{"name": "aged rum", "amount": 1, "unit": "oz"}, {"name": "white rum", "amount": 1, "unit": "oz"}, {"name": "orange curaçao", "amount": 0.5, "unit": "oz"}, {"name": "orgeat", "amount": 0.5, "unit": "oz"}, {"name": "lime juice", "amount": 0.75, "unit": "oz"}, {"name": "dark rum", "amount": 0.5, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Add aged rum, white rum, curaçao, orgeat, and lime juice to a shaker with crushed ice."}, {"order": 2, "action": "Shake briefly to combine and chill."}, {"order": 3, "action": "Dump the contents into a rocks glass."}, {"order": 4, "action": "Float the dark rum on top and garnish with mint and spent lime shell."}]'::jsonb),
  ('old-fashioned', 'Old Fashioned', 'A whiskey classic built on sugar, bitters, and dilution.', 'easy', 1, 'whiskey', '["spirit-forward", "warm", "bittersweet"]'::jsonb, '[{"name": "bourbon", "amount": 2, "unit": "oz"}, {"name": "simple syrup", "amount": 0.25, "unit": "oz"}, {"name": "angostura bitters", "amount": 2, "unit": "dash"}, {"name": "orange peel", "amount": 1, "unit": "piece"}]'::jsonb, '[{"order": 1, "action": "Add bourbon, simple syrup, and bitters to a mixing glass with ice."}, {"order": 2, "action": "Stir until chilled and slightly diluted."}, {"order": 3, "action": "Strain over a large cube in a rocks glass."}, {"order": 4, "action": "Express an orange peel over the drink and use it as garnish."}]'::jsonb),
  ('whiskey-sour', 'Whiskey Sour', 'A balanced whiskey sour with lemon and a silky texture.', 'medium', 1, 'whiskey', '["citrus", "smooth", "balanced"]'::jsonb, '[{"name": "bourbon", "amount": 2, "unit": "oz"}, {"name": "lemon juice", "amount": 0.75, "unit": "oz"}, {"name": "simple syrup", "amount": 0.75, "unit": "oz"}, {"name": "egg white", "amount": 0.75, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Add all ingredients to a shaker without ice and dry shake.", "tip": "Dry shaking first helps build a stable foam."}, {"order": 2, "action": "Add ice and shake again until chilled."}, {"order": 3, "action": "Double strain into a rocks glass over fresh ice."}, {"order": 4, "action": "Top with a few drops of bitters if desired."}]'::jsonb),
  ('boulevardier', 'Boulevardier', 'A whiskey variation on the Negroni with depth and spice.', 'medium', 1, 'whiskey', '["bitter", "rich", "spirit-forward"]'::jsonb, '[{"name": "bourbon", "amount": 1.25, "unit": "oz"}, {"name": "campari", "amount": 1, "unit": "oz"}, {"name": "sweet vermouth", "amount": 1, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Add all ingredients to a mixing glass with ice."}, {"order": 2, "action": "Stir until chilled and glossy."}, {"order": 3, "action": "Strain into a chilled coupe or over ice in a rocks glass."}, {"order": 4, "action": "Garnish with an expressed orange peel."}]'::jsonb),
  ('virgin-mojito', 'Virgin Mojito', 'A non-alcoholic mint cooler with lime and soda.', 'easy', 1, 'non-alcoholic', '["minty", "citrus", "bubbly"]'::jsonb, '[{"name": "lime juice", "amount": 0.75, "unit": "oz"}, {"name": "simple syrup", "amount": 0.5, "unit": "oz"}, {"name": "mint leaves", "amount": 8, "unit": "leaf"}, {"name": "club soda", "amount": 4, "unit": "oz"}]'::jsonb, '[{"order": 1, "action": "Gently muddle mint leaves with lime juice and simple syrup in a tall glass."}, {"order": 2, "action": "Fill the glass with crushed ice."}, {"order": 3, "action": "Top with club soda and stir lightly."}, {"order": 4, "action": "Garnish with fresh mint and a lime wheel."}]'::jsonb),
  ('shirley-temple', 'Shirley Temple', 'A sweet non-alcoholic soda drink with grenadine and citrus.', 'easy', 1, 'non-alcoholic', '["sweet", "fruity", "bubbly"]'::jsonb, '[{"name": "ginger ale", "amount": 4, "unit": "oz"}, {"name": "grenadine", "amount": 0.5, "unit": "oz"}, {"name": "lime juice", "amount": 0.25, "unit": "oz"}, {"name": "cherry", "amount": 1, "unit": "piece"}]'::jsonb, '[{"order": 1, "action": "Fill a highball glass with ice."}, {"order": 2, "action": "Add grenadine and lime juice."}, {"order": 3, "action": "Top with ginger ale and stir gently."}, {"order": 4, "action": "Garnish with a cherry."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

